<a href="https://colab.research.google.com/github/sharunraj14/ICT_Projects/blob/main/Auto_MPG_Numpy_Pandas_Case_Study.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
os.listdir('/content')

['.config',
 'Case_Study_on_Numpy_Pandas_DSA_SMP_Nov_2025.pdf',
 'auto-mpg.csv',
 'sample_data']

In [31]:
import numpy as np
import pandas as pd

df = pd.read_csv('/content/auto-mpg.csv')
df.head(10)

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino  
5       1           ford galaxie 500  
6       1           chevrolet impala  
7       1          plymouth fury iii  
8       1           pontiac catalina  
9       1         amc ambassador dpl

Numpy problems

In [5]:
# 1. Basic Array Operations
mpg = df['mpg'].to_numpy()

mpg_mean = mpg.mean()
mpg_median = np.median(mpg)
mpg_std = mpg.std()
mpg_gt_25 = np.sum(mpg > 25)

mpg_mean, mpg_median, mpg_std, mpg_gt_25


(np.float64(23.514572864321607),
 np.float64(23.0),
 np.float64(7.806159061274433),
 np.int64(158))

In [7]:
# 2. Filtering – cars with more than 6 cylinders
mask = df['cylinders'].to_numpy() > 6
car_names_more_6 = df.loc[mask, 'car name'].tolist()

car_names_more_6[:10]

['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl']

In [8]:
# 3. Percentiles of weight
weight = df['weight'].to_numpy()
np.percentile(weight, [25, 50, 75])


array([2223.75, 2803.5 , 3608.  ])

In [32]:
# 4. Normalize acceleration
acc = df['acceleration'].to_numpy()
acc_norm = (acc - acc.min()) / (acc.max() - acc.min())
acc_norm[:5]

array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952])

In [10]:
# 5. Increase horsepower by 10percent (handle missing values)
hp = pd.to_numeric(df['horsepower'], errors='coerce').to_numpy()
hp_mean = np.nanmean(hp)
hp_clean = np.where(np.isnan(hp), hp_mean, hp)
hp_increased = hp_clean * 1.10

hp_increased[:5]


array([143. , 181.5, 165. , 165. , 154. ])

In [11]:

# 6. Average displacement for origin = 2 (Europe)
origin = df['origin'].to_numpy()
disp = df['displacement'].to_numpy()

avg_disp_europe = disp[origin == 2].mean()
avg_disp_europe

np.float64(109.14285714285714)

In [12]:

# 7. Matrix operations
matrix = df[['mpg', 'horsepower', 'weight']].apply(pd.to_numeric, errors='coerce').fillna(0).to_numpy()
vector = np.array([1, 0.5, -0.2])

dot_product = matrix.dot(vector)
dot_product[:5]

array([-617.8, -641.1, -594.2, -595.6, -602.8])

In [33]:
# 8. Sort by model_year (descending)
sorted_idx = np.argsort(-df['model year'].to_numpy())
df.iloc[sorted_idx]['car name'].head()

397         chevy s-10
396        ford ranger
395      dodge rampage
394          vw pickup
393    ford mustang gl
Name: car name, dtype: object

In [16]:

# 9. Pearson correlation between mpg and weight
np.corrcoef(df['mpg'], df['weight'])[0, 1]

np.float64(-0.8317409332443352)

In [17]:
# 10. Mean mpg grouped by cylinders (NumPy)
cyl = df['cylinders'].to_numpy()
unique_cyl = np.unique(cyl)

mean_mpg_by_cyl = {c: mpg[cyl == c].mean() for c in unique_cyl}
mean_mpg_by_cyl


{np.int64(3): np.float64(20.55),
 np.int64(4): np.float64(29.28676470588235),
 np.int64(5): np.float64(27.366666666666664),
 np.int64(6): np.float64(19.985714285714284),
 np.int64(8): np.float64(14.963106796116506)}

Pandas Problems

In [18]:

# 1. Basic exploration
df.head(10), df.shape, df.describe()

(    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
 0  18.0          8         307.0        130    3504          12.0          70   
 1  15.0          8         350.0        165    3693          11.5          70   
 2  18.0          8         318.0        150    3436          11.0          70   
 3  16.0          8         304.0        150    3433          12.0          70   
 4  17.0          8         302.0        140    3449          10.5          70   
 5  15.0          8         429.0        198    4341          10.0          70   
 6  14.0          8         454.0        220    4354           9.0          70   
 7  14.0          8         440.0        215    4312           8.5          70   
 8  14.0          8         455.0        225    4425          10.0          70   
 9  15.0          8         390.0        190    3850           8.5          70   
 
    origin                   car name  
 0       1  chevrolet chevelle malibu  
 1       1      

In [20]:

# 2. Cars from 1975 with weight < 3000
df_1975 = df[(df['model year'] == 75) & (df['weight'] < 3000)]
df_1975[['car name', 'weight', 'mpg']]

car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

In [21]:
# 3. Handle missing horsepower
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)

df.isna().sum()


/tmp/ipython-input-2081556999.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)


mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [22]:
# 4. Power to weight ratio
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df[['power_to_weight_ratio']].head()


power_to_weight_ratio
0               0.037100
1               0.044679
2               0.043655
3               0.043694
4               0.040591

In [23]:
# 5. Mean mpg by origin
df.groupby('origin')['mpg'].mean()


origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [25]:
# 6. Top 10 cars by mpg
df.sort_values('mpg', ascending=False).head(10)[['car name', 'mpg']]


car name   mpg
322                        mazda glc  46.6
329              honda civic 1500 gl  44.6
325             vw rabbit c (diesel)  44.3
394                        vw pickup  44.0
326               vw dasher (diesel)  43.4
244  volkswagen rabbit custom diesel  43.1
309                        vw rabbit  41.5
330             renault lecar deluxe  40.9
324                       datsun 210  40.8
247                   datsun b210 gx  39.4

In [26]:

# 7. Performance score
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df[['performance_score']].head()

performance_score
0           0.061644
1           0.046710
2           0.057625
3           0.055928
4           0.051754

In [27]:

# 8. Summary by model_year
summary_df = df.groupby('model year')[['mpg', 'weight', 'horsepower']].mean()
summary_df


mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

In [28]:
# 9. Export high mpg cars
high_mpg = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
high_mpg.to_csv('high_mpg_cars.csv', index=False)


In [30]:
# 10. Outliers using IQR
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

outliers = df[(df['mpg'] < Q1 - 1.5 * IQR) | (df['mpg'] > Q3 + 1.5 * IQR)]
outliers[['car name', 'mpg', 'model year']]

car name   mpg  model year
322  mazda glc  46.6          80